when:
  - event: [push, pull_request, manual]

platform: linux/amd64

variables:
  - &rust_image 'rust-builder:1.92.0-ci'

steps:
  - name: format-check
    image: *rust_image
    pull: true
    commands:
      - cargo +nightly fmt --all -- --check
    volumes:
      - /var/cache/sccache:/sccache
      - /var/cache/cargo:/cargo_cache
    environment:
      CARGO_HOME: /cargo_cache
      SCCACHE_DIR: /sccache
      RUSTC_WRAPPER: sccache
      CARGO_INCREMENTAL: 0

  - name: clippy
    image: *rust_image
    pull: true
    commands:
      - cargo clippy --all-targets --all-features -- -D warnings
    volumes:
      - /var/cache/sccache:/sccache
      - /var/cache/cargo:/cargo_cache
    environment:
      CARGO_HOME: /cargo_cache
      SCCACHE_DIR: /sccache
      RUSTC_WRAPPER: sccache
      CARGO_INCREMENTAL: 0

  - name: test
    image: *rust_image
    pull: true
    commands:
      - cargo test --release --all-features
    volumes:
      - /var/cache/sccache:/sccache
      - /var/cache/cargo:/cargo_cache
    environment:
      CARGO_HOME: /cargo_cache
      SCCACHE_DIR: /sccache
      RUSTC_WRAPPER: sccache
      CARGO_INCREMENTAL: 0

  - name: build
    image: *rust_image
    pull: true
    commands:
      - cargo build --release --all-features
    volumes:
      - /var/cache/sccache:/sccache
      - /var/cache/cargo:/cargo_cache
    environment:
      CARGO_HOME: /cargo_cache
      SCCACHE_DIR: /sccache
      RUSTC_WRAPPER: sccache
      CARGO_INCREMENTAL: 0

  - name: doc-check
    image: *rust_image
    pull: true
    commands:
      - cargo doc --no-deps --all-features
    volumes:
      - /var/cache/sccache:/sccache
      - /var/cache/cargo:/cargo_cache
    environment:
      CARGO_HOME: /cargo_cache
      SCCACHE_DIR: /sccache
      RUSTC_WRAPPER: sccache
      CARGO_INCREMENTAL: 0

labels:
  backend: docker
